### ISSUE TITLE
What are Nsingle_cell_reference_data and NBT_simu_cell_order_sccpm?

### ISSUE THREAD

**Issue by gstaryu** [findys/Deconformer#1]
Firstly, thank you very much for your work! I would like to use the `Deconformer` you proposed, but I am encountering some issues in your project.

I understand that I need to generate simulated data first, but in the `deconformer_simluate.py` file of your project, there is the following code:
```
cell_data_directory = "./resource/Nsingle_cell_reference_data"
simulate_save_path = "./resource/simulated_datas/"
df_cell_types = pd.read_csv("./resource/NBT_simu_cell_order_sccpm.txt", sep='\t', index_col=0)
```
Could you provide the data for `Nsingle_cell_reference_data`? Or a link to the data so that I can better replicate the results.

Regarding `NBT_simu_cell_order_sccpm.txt`, I would like to know how this file was generated—whether it was derived from single-cell data or obtained through another method.

Looking forward to your reply.

**Comment by findys** [comment]
Welcome to you and your team to use Deconformer! Today, I uploaded an example of the single-cell reference data. By opening this AnnData, you can see detailed examples within it. All the single-cell reference data used in this study come from public datasets, with Tabula Sapiens being sourced from [this link](https://www.science.org/stoken/author-tokens/ST-495/full). We performed some preprocessing on this dataset, and I have already uploaded a sample of the processed single-cell reference data above. If you need the fully preprocessed data, please email me or the corresponding author, and I will send it to you.

Additionally, `NBT_simu_cell_order_sccpm.txt` is merely the order of cell types used in the adult model in the practical application of this study. This order is used for subsequent predictions, and you can freely modify it as long as it includes all the single-cell reference types.

**Comment by gstaryu** [comment]
Thank you for your answer and the reference data you provided. I will try again.
